general:
  repositorio: "https://gitlab.com/datos-algoritmos-sociedad-itam/CAS-INAI"
  nombre: "CAS INAI"

tema:
  colores:
    verde: "#00715F"
    morado: "#6F197A"

app:
  titulo: "CAS - INAI"
  paginas: ["Visualizaciones", "Consultas"]
